# Generated by Django 4.1.3 on 2022-12-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_chart_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='ASST_TXT_LET_CNT',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='ASST_TXT_NMB_MAX_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='ASST_TXT_NMB_MIN_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='ASST_TXT_USYN',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='AXISY_CNT_MAX_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='AXISY_CNT_MIN_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='AXISY_TTL_LET_CNT_MAX_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='AXISY_TTL_NMB_MAX_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='AXISY_TTL_NMB_MIN_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='AXISY_USYN',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ASST_INDX_TTL_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ASST_INDX_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ASST_TXT_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_AXISX_TTL_EMPH_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_AXISX_TTL_GNRL_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_AXISY_LINE_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_AXISY_TTL_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_IMPN_INDX_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ITEM_EMPH_ALL_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ITEM_EMPH_LEGD1_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ITEM_EMPH_LEGD2_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ITEM_EMPH_LEGD3_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ITEM_EMPH_LEGD4_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ITEM_EMPH_LEGD5_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ITEM_EMPH_PART_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ITEM_GNRL_ALL_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ITEM_GNRL_PART_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ITEM_TXT_EMPH_ALL_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ITEM_TXT_EMPH_PART_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_ITEM_TXT_EMPH_TLTIP_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_MSG_EMPH_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_MSG_GNRL_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_TBL_DSNC_LINE_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_TBL_TTL_BGD_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_TBL_TTL_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_TBL_TXT_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_THRHLD_RFLN_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='COL_THRHLD_TXT_VL',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='ITEM_PART_ALL_USYN',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='ITEM_SET_MAX_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='ITEM_SET_MIN_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='ITEM_SET_USYN',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='ITEM_TXT_NMB_ALL_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='ITEM_TXT_NMB_PART_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='LAST_MDFC_DTTM',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='LEGD_NMB_MAX_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='LEGD_NMB_MIN_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='LEGD_TXT_LET_CNT_MAX_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='LEGD_USYN',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='MDPR_ID',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='MSG_ASST_INDX_CNT',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='MSG_ASST_INDX_LET_CNT_MAX_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='MSG_ASST_INDX_TTL_LET_CNT_MAX_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='MSG_BTN_CNT',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='MSG_CNT',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='MSG_EMPH_CNT',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='MSG_IMPN_INDX_CNT',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='MSG_IMPN_INDX_LET_CNT_MAX_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='MSG_ROW_CNT_MAX_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='MSG_ROW_CNT_MIN_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='MSG_ROW_LET_CNT_MAX_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='MSG_STUS_ICON_CNT',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='MSG_USYN',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='RGDA',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='RGPR_ID',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='TBL_YN',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='THRHLD_RFLN_NMB_MAX_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='THRHLD_RFLN_NMB_MIN_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='THRHLD_TXT_LET_CNT_MAX_VL',
            field=models.FloatField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='THRHLD_USYN',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='chart',
            name='USYN',
            field=models.CharField(blank=True, max_length=33),
        ),
    ]
