# Generated by Django 4.1.3 on 2022-12-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_chart_chart_cd_chart_chart_tpcd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='CHART_TPCD',
            field=models.CharField(blank=True, choices=[('LINE', 'Line'), ('BAR', 'Bar'), ('PIE', 'Pie'), ('TABLE', 'Table'), ('PANEL', 'Panel')], max_length=33, null=True),
        ),
    ]
