from django.db import models

# Create your models here.

class Chart(models.Model):
    TPCD_CHOICES = (('LINE', 'Line'),('BAR', 'Bar'), ('PIE', 'Pie'), ('TABLE', 'Table'), ('PANEL','Panel'))
    #raw_id = models.CharField(max_length=30)
    CHART_CD = models.CharField(max_length=33, blank=True, null = True)
    CHART_TPCD = models.CharField(max_length=33, blank=True, null=True, choices=TPCD_CHOICES )
    COL_ITEM_TXT_EMPH_TLTIP_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_AXISX_TTL_GNRL_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_AXISX_TTL_EMPH_VL = models.CharField(max_length=33, blank=True, null = True)
    ITEM_SET_USYN = models.CharField(max_length=33, blank=True, null = True)
    ITEM_SET_MIN_VL = models.FloatField(max_length=33, blank=True, null = True)
    ITEM_SET_MAX_VL = models.FloatField(max_length=33, blank=True, null = True)
    AXISY_USYN = models.CharField(max_length=33, blank=True, null = True)
    AXISY_CNT_MIN_VL = models.FloatField(max_length=33, blank=True, null = True)
    AXISY_CNT_MAX_VL = models.FloatField(max_length=33, blank=True, null = True)
    AXISY_TTL_NMB_MIN_VL = models.FloatField(max_length=33, blank=True, null = True)
    AXISY_TTL_NMB_MAX_VL = models.FloatField(max_length=33, blank=True, null = True)
    AXISY_TTL_LET_CNT_MAX_VL = models.FloatField(max_length=33, blank=True, null = True)
    COL_AXISY_TTL_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_AXISY_LINE_VL = models.CharField(max_length=33, blank=True, null = True)
    LEGD_USYN = models.CharField(max_length=33, blank=True, null = True)
    LEGD_NMB_MIN_VL = models.FloatField(max_length=33, blank=True, null = True)
    LEGD_NMB_MAX_VL = models.FloatField(max_length=33, blank=True, null = True)
    LEGD_TXT_LET_CNT_MAX_VL = models.FloatField(max_length=33, blank=True, null = True)
    COL_ITEM_EMPH_LEGD1_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_ITEM_EMPH_LEGD2_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_ITEM_EMPH_LEGD3_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_ITEM_EMPH_LEGD4_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_ITEM_EMPH_LEGD5_VL = models.CharField(max_length=33, blank=True, null = True)
    THRHLD_USYN = models.CharField(max_length=33, blank=True, null = True)
    THRHLD_RFLN_NMB_MIN_VL = models.FloatField(max_length=33, blank=True, null = True)
    THRHLD_RFLN_NMB_MAX_VL = models.FloatField(max_length=33, blank=True, null = True)
    THRHLD_TXT_LET_CNT_MAX_VL = models.FloatField(max_length=33, blank=True, null = True)
    COL_THRHLD_RFLN_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_THRHLD_TXT_VL = models.CharField(max_length=33, blank=True, null = True)
    ASST_TXT_USYN = models.CharField(max_length=33, blank=True, null = True)
    ASST_TXT_NMB_MIN_VL = models.FloatField(max_length=33, blank=True, null = True)
    ASST_TXT_NMB_MAX_VL = models.FloatField(max_length=33, blank=True, null = True)
    ASST_TXT_LET_CNT = models.FloatField(max_length=33, blank=True, null = True)
    COL_ASST_TXT_VL = models.CharField(max_length=33, blank=True, null = True)
    MSG_USYN = models.CharField(max_length=33, blank=True, null = True)
    MSG_ROW_CNT_MAX_VL = models.FloatField(max_length=33, blank=True, null = True)
    MSG_ROW_CNT_MIN_VL = models.FloatField(max_length=33, blank=True, null = True)
    MSG_ROW_LET_CNT_MAX_VL = models.FloatField(max_length=33, blank=True, null = True)
    MSG_EMPH_CNT = models.FloatField(max_length=33, blank=True, null = True)
    MSG_CNT = models.FloatField(max_length=33, blank=True, null = True)
    MSG_IMPN_INDX_CNT = models.FloatField(max_length=33, blank=True, null = True)
    MSG_ASST_INDX_CNT = models.FloatField(max_length=33, blank=True, null = True)
    MSG_IMPN_INDX_LET_CNT_MAX_VL = models.FloatField(max_length=33, blank=True, null = True)
    MSG_ASST_INDX_TTL_LET_CNT_MAX_VL = models.FloatField(max_length=33, blank=True, null = True)
    MSG_ASST_INDX_LET_CNT_MAX_VL = models.FloatField(max_length=33, blank=True, null = True)
    MSG_STUS_ICON_CNT = models.FloatField(max_length=33, blank=True, null = True)
    MSG_BTN_CNT = models.FloatField(max_length=33, blank=True, null = True)
    COL_MSG_GNRL_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_MSG_EMPH_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_IMPN_INDX_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_ASST_INDX_TTL_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_ASST_INDX_VL = models.CharField(max_length=33, blank=True, null = True)
    ITEM_PART_ALL_USYN = models.CharField(max_length=33, blank=True, null = True)
    ITEM_TXT_NMB_PART_VL = models.FloatField(max_length=33, blank=True, null = True)
    ITEM_TXT_NMB_ALL_VL = models.FloatField(max_length=33, blank=True, null = True)
    COL_ITEM_GNRL_PART_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_ITEM_GNRL_ALL_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_ITEM_EMPH_PART_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_ITEM_EMPH_ALL_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_ITEM_TXT_EMPH_PART_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_ITEM_TXT_EMPH_ALL_VL = models.CharField(max_length=33, blank=True, null = True)
    TBL_YN = models.CharField(max_length=33, blank=True, null = True)
    COL_TBL_TXT_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_TBL_DSNC_LINE_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_TBL_TTL_VL = models.CharField(max_length=33, blank=True, null = True)
    COL_TBL_TTL_BGD_VL = models.CharField(max_length=33, blank=True, null = True)
    USYN = models.CharField(max_length=33, blank=True, null = True)
    RGPR_ID = models.CharField(max_length=33, blank=True, null = True)
    RGDA = models.CharField(max_length=33, blank=True, null = True)
    MDPR_ID = models.CharField(max_length=33, blank=True, null = True)
    LAST_MDFC_DTTM = models.CharField(max_length=33, blank=True, null = True)

    def __str__(self):
        return str(self.id)
